camunda.bpm:
  admin-user:
    id: kermit
    password: superSecret
    firstName: Kermit
  filter:
    create: All tasks
  database:
    type: h2
    
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: camunda-demo-service
  jersey: 
    application-path: /engine-rest 
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:D:/projects/workspace_camundademo/camunda-demo/camunda-springbootdemo/src/main/resources/camunda_demo
    user: !!str "sa"
    password: !!str "123456"

